name: Sync LeetCode (daily commits)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"   # 17:00 UTC daily (≈ 10 AM PDT / 9 AM PST)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run LeetCode Sync (makes commit via API)
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: daily_challange_solutions
          verbose: true
          commit-header: "[temp-sync]"

      - name: Pull the new commit the action just pushed
        run: |
          git remote set-url origin "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git"
          git checkout "${{ github.ref_name }}"
          git fetch origin "${{ github.ref_name }}"
          git pull --ff-only origin "${{ github.ref_name }}"

      - name: Amend commit message and push (just date)
        run: |
          DATE="$(TZ=America/Los_Angeles date +'%Y-%m-%d')"
          NEWMSG="Daily_Challenge_${DATE}"
          echo "New commit message: $NEWMSG"

          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git commit --amend -m "$NEWMSG"
          git push --force